services:
  dev-postgres:
    image: postgres:latest
    container_name: dev-db
    ports:
      - "5432:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - dev-network
  dev-pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    env_file:
      - ./.env
    ports:
      - "5050:80"
    networks:
      - dev-network
volumes:
  dev_postgres_data:

networks:
  dev-network:
    driver: bridge
