services:
  # Test PostgreSQL database
  test-postgres:
    image: postgres:16-alpine
    container_name: test-db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password_123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  # Redis for session storage (if needed)
  test-redis:
    image: redis:7-alpine
    container_name: test-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - test_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - test-network

  # Test runner container (optional - for running tests in isolated environment)
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-runner
    environment:
      DATABASE_URL: postgres://postgres:test_password_123@test-postgres:5432/test_db
      REDIS_URL: redis://test-redis:6379
      RUST_LOG: debug
      RUST_BACKTRACE: 1
    depends_on:
      test-postgres:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    volumes:
      - .:/workspace
      - test_target_cache:/workspace/target
      - test_cargo_cache:/usr/local/cargo/registry
    working_dir: /workspace
    networks:
      - test-network

  # Test database with specific version for compatibility testing
  test-postgres-14:
    image: postgres:14-alpine
    container_name: test-db-14
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password_123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5434:5432"
    volumes:
      - test_postgres_14_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  # Integration test environment with Node.js for TypeScript client testing
  typescript-test:
    image: node:20-alpine
    container_name: ts-test
    environment:
      API_BASE_URL: http://test-api:3000
      NODE_ENV: test
    volumes:
      - ./clientlib:/app
      - ts_node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run test:integration"
    depends_on:
      - test-api
    networks:
      - test-network
    profiles:
      - e2e

  # Test API server
  test-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: test-api
    command:
      [
        "server",
        "--config",
        "assets/config/config.test.jsonc",
        "--secrets",
        "assets/config/config.secrets.test.jsonc",
      ]
    environment:
      DATABASE_URL: postgres://postgres:test_password_123@test-postgres:5432/test_db
      REDIS_URL: redis://test-redis:6379
      RUST_LOG: info
      PORT: 3000
    ports:
      - "3001:3000"
    depends_on:
      test-postgres:
        condition: service_healthy
    networks:
      - test-network
    profiles:
      - e2e
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Performance testing with wrk
  perf-test:
    image: williamyeh/wrk
    container_name: perf-test
    command: >
      sh -c "
        echo 'Waiting for API to be ready...' &&
        sleep 10 &&
        echo 'Running performance tests...' &&
        wrk -t4 -c100 -d30s --timeout 10s http://test-api:3000/health &&
        echo 'Health endpoint test completed' &&
        wrk -t2 -c10 -d10s --timeout 10s -s /scripts/register.lua http://test-api:3000/
      "
    volumes:
      - ./scripts/perf:/scripts
    depends_on:
      - test-api
    networks:
      - test-network
    profiles:
      - e2e

  # Prometheus for metrics collection during testing
  test-prometheus:
    image: prom/prometheus:latest
    container_name: test-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./config/prometheus-test.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=1h"
      - "--web.enable-lifecycle"
    networks:
      - test-network
    profiles:
      - monitoring

volumes:
  test_postgres_data:
    driver: local
  test_postgres_14_data:
    driver: local
  test_redis_data:
    driver: local
  test_target_cache:
    driver: local
  test_cargo_cache:
    driver: local
  ts_node_modules:
    driver: local

networks:
  test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
