[package]
name = "cli"
version = "0.1.0"
authors = [
  "William Brown <william@blackhats.net.au>, Ben Wishovich <ben@benw.is>",
]
edition = "2021"
license = "MPL-2.0"

[dependencies]
clap.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
server = { path = "../server" }

[features]
default = []
